name: Push Main - Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        run: |
          TAG="${{ steps.version.outputs.version }}"
          echo "Creating tag: $TAG"
          
          # Delete existing tag if it exists (locally and remotely)
          git tag -d "$TAG" 2>/dev/null || true
          git push --delete origin "$TAG" 2>/dev/null || true
          
          # Create and push new tag
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: push-tag_release-cli.yaml
          ref: ${{ github.ref }} 
          wait_interval: 10
          propagate_failure: true